### ISSUE TITLE
Couldn't read loot table, NoClassDefFoundError

### ISSUE THREAD

**Issue by max-kamps** [FabricMC/fabric-example-mod#11]
Hi!
I don't know if this is the right repo for this issue, since I don't know which fabric component is at fault here. In that case feel free to close this and I'll move to a different one.

I downloaded the example mod and changed it to use the latest version, but when starting the game, there are tons of errors of the following form:

```
[19:33:47] [Server thread/ERROR]: Couldn't read loot table minecraft:blocks/spruce_sign from minecraft:loot_tables/blocks/spruce_sign.json
java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.world.loot.entry.LootEntries
	at net.minecraft.world.loot.entry.LootEntries$Serializer.method_407(LootEntries.java:47) ~[minecraft-1.14%20Pre-Release%201-mapped-3.jar:?]
	at net.minecraft.world.loot.entry.LootEntries$Serializer.deserialize(LootEntries.java:41) ~[minecraft-1.14%20Pre-Release%201-mapped-3.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.0.jar:?]
	at net.minecraft.util.JsonHelper.deserialize(JsonHelper.java:440) ~[minecraft-1.14%20Pre-Release%201-mapped-3.jar:?]
	at net.minecraft.util.JsonHelper.deserialize(JsonHelper.java:448) ~[minecraft-1.14%20Pre-Release%201-mapped-3.jar:?]
	at net.minecraft.world.loot.LootPool$Serializer.method_358(LootPool.java:173) ~[minecraft-1.14%20Pre-Release%201-mapped-3.jar:?]
	at net.minecraft.world.loot.LootPool$Serializer.deserialize(LootPool.java:169) ~[minecraft-1.14%20Pre-Release%201-mapped-3.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.0.jar:?]
	at net.minecraft.util.JsonHelper.deserialize(JsonHelper.java:440) ~[minecraft-1.14%20Pre-Release%201-mapped-3.jar:?]
	at net.minecraft.util.JsonHelper.deserialize(JsonHelper.java:456) ~[minecraft-1.14%20Pre-Release%201-mapped-3.jar:?]
	at net.minecraft.world.loot.LootSupplier$Serializer.method_340(LootSupplier.java:215) ~[minecraft-1.14%20Pre-Release%201-mapped-3.jar:?]
	at net.minecraft.world.loot.LootSupplier$Serializer.deserialize(LootSupplier.java:211) ~[minecraft-1.14%20Pre-Release%201-mapped-3.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.0.jar:?]
	at net.minecraft.util.JsonHelper.deserialize(JsonHelper.java:493) ~[minecraft-1.14%20Pre-Release%201-mapped-3.jar:?]
	at net.minecraft.util.JsonHelper.deserialize(JsonHelper.java:518) ~[minecraft-1.14%20Pre-Release%201-mapped-3.jar:?]
	at net.minecraft.util.JsonHelper.deserialize(JsonHelper.java:538) ~[minecraft-1.14%20Pre-Release%201-mapped-3.jar:?]
	at net.minecraft.world.loot.LootManager.apply(LootManager.java:63) ~[minecraft-1.14%20Pre-Release%201-mapped-3.jar:?]
	at net.minecraft.resource.SynchronousResourceReloadListener.method_18235(SynchronousResourceReloadListener.java:12) ~[minecraft-1.14%20Pre-Release%201-mapped-3.jar:?]
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705) ~[?:1.8.0_212]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687) ~[?:1.8.0_212]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_212]
	at net.minecraft.resource.ResourceReloadHandler.method_18365(ResourceReloadHandler.java:71) ~[minecraft-1.14%20Pre-Release%201-mapped-3.jar:?]
	at net.minecraft.server.ServerTask.run(ServerTask.java:18) [minecraft-1.14%20Pre-Release%201-mapped-3.jar:?]
	at net.minecraft.util.ThreadExecutor.runSafely(ThreadExecutor.java:135) [minecraft-1.14%20Pre-Release%201-mapped-3.jar:?]
	at net.minecraft.util.GameTaskQueue.runSafely(GameTaskQueue.java:23) [minecraft-1.14%20Pre-Release%201-mapped-3.jar:?]
	at net.minecraft.util.ThreadExecutor.executeQueuedTask(ThreadExecutor.java:114) [minecraft-1.14%20Pre-Release%201-mapped-3.jar:?]
	at net.minecraft.server.MinecraftServer.executeQueuedTask(MinecraftServer.java:692) [minecraft-1.14%20Pre-Release%201-mapped-3.jar:?]
	at net.minecraft.util.ThreadExecutor.waitFor(ThreadExecutor.java:123) [minecraft-1.14%20Pre-Release%201-mapped-3.jar:?]
	at net.minecraft.server.MinecraftServer.reloadDataPacks(MinecraftServer.java:1456) [minecraft-1.14%20Pre-Release%201-mapped-3.jar:?]
	at net.minecraft.server.MinecraftServer.method_3800(MinecraftServer.java:447) [minecraft-1.14%20Pre-Release%201-mapped-3.jar:?]
	at net.minecraft.server.integrated.IntegratedServer.method_3735(IntegratedServer.java:79) [minecraft-1.14%20Pre-Release%201-mapped-3.jar:?]
	at net.minecraft.server.integrated.IntegratedServer.setupServer(IntegratedServer.java:104) [minecraft-1.14%20Pre-Release%201-mapped-3.jar:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:602) [minecraft-1.14%20Pre-Release%201-mapped-3.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

These are the versions I am using:
```
minecraft_version=1.14 Pre-Release 1
yarn_mappings=1.14 Pre-Release 1+build.3
loader_version=0.4.0+build.121
fabric_version=0.2.7+build.122
```

Cheers!

**Comment by max-kamps** [comment]
Updated to pre-release 2 and the latest mappings, can't replicate.
Guess I'll close this :man_shrugging:
