### ISSUE TITLE
VersionParsingException being thrown on runClient

### ISSUE THREAD

**Issue by Lucas-Cerqueira** [FabricMC/fabric-example-mod#137]
I am getting the following error when running the `runClient` task:

```
> Task :runClient FAILED
[00:22:42] [INFO] [FabricLoader/GameProvider]: Loading for game Minecraft minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.63-v2
[00:22:43] [main/INFO] (FabricLoader/GameProvider) Loading for game Minecraft minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.63-v2
Exception in thread "main" java.lang.RuntimeException: net.fabricmc.loader.api.VersionParsingException: Could not parse version number component 'minecraft'!
	at net.fabricmc.loader.impl.metadata.BuiltinModMetadata$Builder.<init>(BuiltinModMetadata.java:177)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.getBuiltinMods(MinecraftGameProvider.java:113)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:94)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:199)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:183)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:119)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Caused by: net.fabricmc.loader.api.VersionParsingException: Could not parse version number component 'minecraft'!
	at net.fabricmc.loader.impl.util.version.SemanticVersionImpl.<init>(SemanticVersionImpl.java:108)
	at net.fabricmc.loader.impl.util.version.VersionParser.parseSemantic(VersionParser.java:45)
Caused by: net.fabricmc.loader.api.VersionParsingException: Could not parse version number component 'minecraft'!

	at net.fabricmc.loader.impl.metadata.BuiltinModMetadata$Builder.<init>(BuiltinModMetadata.java:175)
	... 8 more
Caused by: java.lang.NumberFormatException: For input string: "minecraft"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:660)
Caused by: java.lang.NumberFormatException: For input string: "minecraft"

	at java.base/java.lang.Integer.parseInt(Integer.java:778)
	at net.fabricmc.loader.impl.util.version.SemanticVersionImpl.<init>(SemanticVersionImpl.java:102)
	... 10 more
```

gradle.properties
```
# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://fabricmc.net/versions.html
minecraft_version=1.17.1
yarn_mappings=1.17.1+build.63
loader_version=0.12.4

# Mod Properties
mod_version = 1.0.0
maven_group = com.example
archives_base_name = fabric-example-mod

# Dependencies
fabric_version=0.41.3+1.17
```

Apparently "minecraft-" is being appended to the game version and fails on `VersionParser.parseSemantic(version)` inside the `Builder` constructor.

**Comment by SirEnder125** [comment]
You may have better luck with questions over at https://github.com/FabricMC/fabric/discussions.

**Comment by Lucas-Cerqueira** [comment]
Thanks @SirEnder125 for the reply. I will try posting there.

**Comment by Technici4n** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
