### ISSUE TITLE
I am Not Casting it How do I fix? I don't Want My Mod To Require FabricAPI

### ISSUE THREAD

**Issue by JacktheDevel0per** [FabricMC/fabric-example-mod#142]
Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'main' provided by 'filledtothebrim'
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 12 more
Caused by: net.fabricmc.loader.api.LanguageAdapterException: Class com.Jack.FilledToTheBrim.FilledToTheBrim cannot be cast to net.fabricmc.api.ModInitializer!
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:63)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	... 13 more

**Comment by JacktheDevel0per** [comment]
wait is this a Loader Api or Fabric Api?

**Comment by OroArmor** [comment]
Fabric Loader is different from Fabric API. You mod initializer needs to extend `ModInitializer` or you need to change the entrypoint to be a lambda method, like you would in java.

**Comment by JacktheDevel0per** [comment]
ahhh, and Thanks Saw you From Discord

**Comment by caelthegreat236** [comment]
Caused by: net.fabricmc.loader.api.LanguageAdapterException: java.lang.ClassNotFoundException: net.cael.orbitalmod.TutorialModClient
how do I fix my mod ?

**Comment by JacktheDevel0per** [comment]
Seems like you are trying to use a class that does not exist? Could be another issue, but did you mend or make your own issue or did you men's to put it here?

**Comment by PunChen** [comment]
> Caused by: net.fabricmc.loader.api.LanguageAdapterException: java.lang.ClassNotFoundException: net.cael.orbitalmod.TutorialModClient how do I fix my mod ?

i have the same issue
