### ISSUE TITLE
Incompatibility with apple silicone

### ISSUE THREAD

**Issue by Xeretis** [FabricMC/fabric-example-mod#150]
I am unable to set up a dev environment using this template due to the LWJGL natives being incompatible. Although LWJGL doesn't provide apple silicone compatible versions yet, there are ways to make it work with Minecraft, but I was unable to apply these methods to the dev environment.

An example of such methods: https://gist.github.com/vortck/4ef2d8f1dd2a63689b82a5b05f7b1b37

The error my ide throws on launch:
```
[16:33:20] [Render thread/ERROR] (FabricLoader) Minecraft has crashed!
 net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:610) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
	at net.minecraft.util.SystemDetails.addSection(SystemDetails.java:65) ~[minecraft-project-@-mapped.jar:?]
	at net.minecraft.client.MinecraftClient.addSystemDetailsToCrashReport(MinecraftClient.java:2420) ~[minecraft-project-@-mapped.jar:?]
	at net.minecraft.client.MinecraftClient.addSystemDetailsToCrashReport(MinecraftClient.java:2415) ~[minecraft-project-@-mapped.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:208) ~[minecraft-project-@-mapped.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
	... 3 more

Process finished with exit code 1
```

Technical details:
- SoC: Apple M1
- IDE: IntelliJ IDEA Ultimate 21.2.3
- Mc version: 1.18.1
- Yarn mappings: 1.18.1+build.1
- Loader version: 0.12.12
- Fabric version: 0.44.0+1.18

The project I was using is cloned directly from here.

**Comment by modmuss50** [comment]
See my comment here: https://github.com/FabricMC/fabric-loom/issues/426#issuecomment-878204323 for help with this, let me know if you have any issues.

I am working on a full fix for this that will just work here: https://github.com/FabricMC/fabric-loom/pull/554
