### ISSUE TITLE
Uncaught exception in thread "Main" issue?

### ISSUE THREAD

**Issue by FabricStuff** [FabricMC/fabric-example-mod#171]
Uncaught exception in thread "main"
java.lang.RuntimeException: Mixin transformation of net.minecraft.client.main.Main failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:414)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [fabric-registry-sync-v0.mixins.json:MixinDynamicRegistryManager] from phase [DEFAULT] in config [fabric-registry-sync-v0.mixins.json] from mod [fabric-registry-sync-v0] FAILED during PREPARE
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinPrepareError(MixinProcessor.java:585)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:543)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247)
	... 6 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Mixin target type mismatch: net.minecraft.class_5455 is an interface in org.spongepowered.asm.mixin.transformer.MixinInfo$SubType$Standard@52a36910
	at org.spongepowered.asm.mixin.transformer.MixinInfo$SubType.validateTarget(MixinInfo.java:553)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.getTargetClass(MixinInfo.java:1027)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:1008)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.parseTargets(MixinInfo.java:896)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:869)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:777)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540)
	... 12 more

Is there any known way to solve this? My java ver. is already to the newest and I can play normally when I have no mods in my mod folder (and it's ONLY the Fabric API wich causes this)

**Comment by HurricaneInteractive** [comment]
I managed to fix this for myself, not sure if you have the same problem. In the [yourmodid.mixins.json](https://github.com/FabricMC/fabric-example-mod/blob/1.18/src/main/resources/modid.mixins.json) file. I think when I started renaming files Intelij was trying to be too smart and updated the `client` array from have a value of `ExampleMixin` to be `yourmodid.some.path.mixins.ExampleMixin`. Which completely broke my build.

So make sure that `client` array doesn't contain the package name as a prefix.

```json
{
  "required": true,
  "minVersion": "0.8",
  "package": "yourmodid.some.path.mixin",
  "compatibilityLevel": "JAVA_17",
  "mixins": [
  ],
  "client": [
    "ExampleMixin" // good
    "yourmodid.some.path.mixin.ExampleMixin"  // bad
  ],
  "injectors": {
    "defaultRequire": 1
  }
}
```

You can test if the issue is in this `.mixins.json` file by going into the `fabric.mod.json` and changing the `mixins` array to be empty and running the debug process again.

**Comment by Technici4n** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
