### ISSUE TITLE
Error making profile to 22w18a

### ISSUE THREAD

**Issue by Armindus** [FabricMC/fabric-example-mod#182]
Hi , i've recently create a profile for last snapshot and this is what happen when i try to launch it.

Uncaught exception in thread "main"
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Unsupported class file major version 63
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 63
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
	at net.fabricmc.tinyremapper.TinyRemapper.analyze(TinyRemapper.java:571)
	at net.fabricmc.tinyremapper.TinyRemapper.access$400(TinyRemapper.java:73)
	at net.fabricmc.tinyremapper.TinyRemapper$2.visitFile(TinyRemapper.java:525)
	at net.fabricmc.tinyremapper.TinyRemapper$2.visitFile(TinyRemapper.java:521)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2811)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2882)
	at net.fabricmc.tinyremapper.TinyRemapper.readFile(TinyRemapper.java:521)
	at net.fabricmc.tinyremapper.TinyRemapper.access$200(TinyRemapper.java:73)
	at net.fabricmc.tinyremapper.TinyRemapper$1$1.get(TinyRemapper.java:492)
	at net.fabricmc.tinyremapper.TinyRemapper$1$1.get(TinyRemapper.java:488)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 3 more

Dunno how to resolve it ,  if someone can help me i would appreciate it :)

**Comment by modmuss50** [comment]
You have to use fabric loader 0.14.4. It can be manually selected in the installer

**Comment by Armindus** [comment]
Really thanks mate :) i was beginning stressing out :)
