### ISSUE TITLE
Trying to get direction of player

### ISSUE THREAD

**Issue by Sxmourai** [FabricMC/fabric-example-mod#210]
Hello, I'm trying to get the yaw of player.
In the client entry point I have this :
ClientTickEvents.START_CLIENT_TICK.register(client -> {
    PlayerEntity pe = client.player;
    double yaw = pe.getYaw();
}
When I launch the :runClient with Intellij, MineCraft opens, and automaticly stops before the loading.
I tried with pe.getYaw(); and didn't have any issues.
The error is :
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':runClient'. **<31 lines>**
Caused by: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.2\jbr\bin\java.exe'' finished with non-zero exit value -1
	at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:415)
	at org.gradle.process.internal.DefaultJavaExecAction.execute(DefaultJavaExecAction.java:52)
	at org.gradle.api.tasks.JavaExec.exec(JavaExec.java:165)
	at net.fabricmc.loom.task.AbstractRunTask.exec(AbstractRunTask.java:84) **<116 lines>**

I've found no other issues reporting this, so I post it.

**Comment by Juuxel** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
