### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by vtf6259** [FabricMC/fabric-example-mod#250]
When i start minecraft it crashes on startup the log is
[16:35:43] [main/INFO] (FabricLoader/GameProvider) Loading Minecraft 1.19.4 with Fabric Loader 0.14.19
[16:35:43] [ForkJoinPool-1-worker-1/WARN] (FabricLoader/Metadata) Mod firstmod uses the version ${version} which isn't compatible with Loader's extended semantic version format (Could not parse version number component '${version}'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[16:35:43] [main/INFO] (FabricLoader) Loading 46 mods:
        - fabric-api 0.79.0+1.19.4
        - fabric-api-base 0.4.24+9ff28bcef4
        - fabric-api-lookup-api-v1 1.6.25+49abcf7ef4
        - fabric-biome-api-v1 13.0.7+348a9c64f4
        - fabric-block-api-v1 1.0.6+e022e5d1f4
        - fabric-blockrenderlayer-v1 1.1.34+c2e6f674f4
        - fabric-client-tags-api-v1 1.0.15+1134c5b8f4
        - fabric-command-api-v2 2.2.6+e719b857f4
        - fabric-content-registries-v0 3.5.9+ae0966baf4
        - fabric-convention-tags-v1 1.4.1+9a7c5daaf4
        - fabric-crash-report-info-v1 0.2.15+aeb40ebef4
        - fabric-data-generation-api-v1 11.4.0+6cebf059f4
        - fabric-dimensions-v1 2.1.45+7f87f8faf4
        - fabric-entity-events-v1 1.5.13+e45f7c65f4
        - fabric-events-interaction-v0 0.4.43+a1ccd7bff4
        - fabric-game-rule-api-v1 1.0.33+a1ccd7bff4
        - fabric-gametest-api-v1 1.2.4+ae0966baf4
        - fabric-item-api-v1 2.1.17+09a3510cf4
        - fabric-item-group-api-v1 3.0.5+043f9acff4
        - fabric-key-binding-api-v1 1.0.33+c477957ef4
        - fabric-lifecycle-events-v1 2.2.15+5da15ca1f4
        - fabric-loot-api-v2 1.1.27+75e98211f4
        - fabric-message-api-v1 5.1.1+1ee8be40f4
        - fabric-mining-level-api-v1 2.1.39+49abcf7ef4
        - fabric-models-v0 0.3.30+11ba9c3bf4
        - fabric-networking-api-v1 1.3.1+a6f3ccfaf4
        - fabric-object-builder-api-v1 7.0.3+63b515f4f4
        - fabric-particles-v1 1.0.23+f1e4495bf4
        - fabric-recipe-api-v1 1.0.8+a1ccd7bff4
        - fabric-registry-sync-v0 2.2.0+670e8ac6f4
        - fabric-renderer-api-v1 2.2.5+81e8c576f4
        - fabric-renderer-indigo 1.1.1+81e8c576f4
        - fabric-rendering-data-attachment-v1 0.3.28+afca2f3ef4
        - fabric-rendering-fluids-v1 3.0.21+f1e4495bf4
        - fabric-rendering-v1 2.1.1+8f878217f4
        - fabric-resource-conditions-api-v1 2.3.1+e6c7d4eef4
        - fabric-resource-loader-v0 0.11.2+1e1fb126f4
        - fabric-screen-api-v1 1.0.45+8c25edb4f4
        - fabric-screen-handler-api-v1 1.3.20+5da15ca1f4
        - fabric-sound-api-v1 1.0.9+75e98211f4
        - fabric-transfer-api-v1 3.1.1+da9bb835f4
        - fabric-transitive-access-wideners-v1 3.0.3+63b515f4f4
        - fabricloader 0.14.19
        - firstmod ${version}
        - java 17
        - minecraft 1.19.4
[16:35:44] [main/INFO] (FabricLoader/Mixin) SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/vtf62/.gradle/caches/modules-2/files-2.1/net.fabricmc/sponge-mixin/0.12.4+mixin.0.8.5/e13b4069fe3555969811d4474f78576c707bbe1c/sponge-mixin-0.12.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[16:35:44] [main/INFO] (FabricLoader/Mixin) Loaded Fabric development mappings for mixin remapper!
[16:35:44] [main/INFO] (FabricLoader/Mixin) Compatibility level set to JAVA_17
[16:35:49] [Datafixer Bootstrap/INFO] (Minecraft) 180 Datafixer optimizations took 126 milliseconds
[16:35:51] [Render thread/INFO] (Minecraft) Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[16:35:51] [Render thread/ERROR] (Minecraft) Failed to verify authentication
 com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
        at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:56) ~[authlib-3.18.38.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:156) ~[authlib-3.18.38.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.<init>(YggdrasilUserApiService.java:55) ~[authlib-3.18.38.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:161) ~[authlib-3.18.38.jar:?]
        at net.minecraft.client.MinecraftClient.createUserApiService(MinecraftClient.java:712) ~[minecraft-merged-project-root-1.19.4-net.fabricmc.yarn.1_19_4.1.19.4+build.2-v2.jar:?]
        at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:506) ~[minecraft-merged-project-root-1.19.4-net.fabricmc.yarn.1_19_4.1.19.4+build.2-v2.jar:?]
        at net.minecraft.client.main.Main.main(Main.java:178) ~[minecraft-merged-project-root-1.19.4-net.fabricmc.yarn.1_19_4.1.19.4+build.2-v2.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.19.jar:?]
        at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
        at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:85) ~[authlib-3.18.38.jar:?]
        at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:48) ~[authlib-3.18.38.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:129) ~[authlib-3.18.38.jar:?]
        ... 9 more
[16:35:51] [Render thread/INFO] (Minecraft) Setting user: Player995
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2023-04-27 16:35:51
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'firstmod'!
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
        at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:526)
        at net.minecraft.client.main.Main.main(Main.java:178)
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
        at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
        at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'main' provided by 'firstmod'
        at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56)
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
        ... 8 more
Caused by: net.fabricmc.loader.api.LanguageAdapterException: java.lang.ClassNotFoundException: net.virgilsfirstmod.mod.firstmod
        at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:52)
        at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
        at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
        ... 9 more
Caused by: java.lang.ClassNotFoundException: net.virgilsfirstmod.mod.firstmod
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)
        at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
        ... 11 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
        at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:526)

-- Initialization --
Details:
        Modules:
                ADVAPI32.dll:Advanced Windows 32 Base API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation
                CRYPT32.dll:Crypto API32:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                CRYPTBASE.dll:Base cryptographic API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                CRYPTSP.dll:Cryptographic Service Provider API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                DBGHELP.DLL:Windows Image Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                DNSAPI.dll:DNS Client API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                GDI32.dll:GDI Client DLL:10.0.22621.608 (WinBuild.160101.0800):Microsoft Corporation
                IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.22621.1344 (WinBuild.160101.0800):Microsoft Corporation
                IPHLPAPI.DLL:IP Helper API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.22621.1485 (WinBuild.160101.0800):Microsoft Corporation
                KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.22621.1485 (WinBuild.160101.0800):Microsoft Corporation
                MpOav.dll:IOfficeAntiVirus Module:4.18.2304.8 (WinBuild.160101.0800):Microsoft Corporation
                NSI.dll:NSI User-mode interface DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                NTASN1.dll:Microsoft ASN.1 API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                OLEAUT32.dll:OLEAUT32.DLL:10.0.22621.608 (WinBuild.160101.0800):Microsoft Corporation
                Ole32.dll:Microsoft OLE for Windows:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                PSAPI.DLL:Process Status Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                Pdh.dll:Windows Performance Data Helper DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                RPCRT4.dll:Remote Procedure Call Runtime:10.0.22621.1344 (WinBuild.160101.0800):Microsoft Corporation
                SHCORE.dll:SHCORE:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                SHELL32.dll:Windows Shell Common Dll:10.0.22621.755 (WinBuild.160101.0800):Microsoft Corporation
                USER32.dll:Multi-User Windows USER API Client DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                USERENV.dll:Userenv:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                VCRUNTIME140.dll:Microsoft? C Runtime Library:14.27.29112.0 built by: vcwrkspc:Microsoft Corporation
                VERSION.dll:Version Checking and File Installation Libraries:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                WINHTTP.dll:Windows HTTP Services:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                WINMM.dll:MCI API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                amsi.dll:Anti-Malware Scan Interface:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                bcrypt.dll:Windows Cryptographic Primitives Library:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.22621.1344 (WinBuild.160101.0800):Microsoft Corporation
                clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
                combase.dll:Microsoft COM for Windows:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                dbgcore.DLL:Windows Core Debugging Helpers:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                dhcpcsvc.DLL:DHCP Client Service:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                dhcpcsvc6.DLL:DHCPv6 Client:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                dt_socket.dll:OpenJDK Platform binary:17.0.7.0:Eclipse Adoptium
                fwpuclnt.dll:FWP/IPsec User-Mode API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                gdi32full.dll:GDI Client DLL:10.0.22621.1344 (WinBuild.160101.0800):Microsoft Corporation
                iertutil.dll:Run time utility for Internet Explorer:11.00.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                java.dll:OpenJDK Platform binary:17.0.7.0:Eclipse Adoptium
                java.exe:OpenJDK Platform binary:17.0.7.0:Eclipse Adoptium
                jdwp.dll:OpenJDK Platform binary:17.0.7.0:Eclipse Adoptium
                jemalloc.dll
                jimage.dll:OpenJDK Platform binary:17.0.7.0:Eclipse Adoptium
                jli.dll:OpenJDK Platform binary:17.0.7.0:Eclipse Adoptium
                jna1607238035960174688.dll:JNA native library:6.1.4:Java(TM) Native Access (JNA)
                jvm.dll:OpenJDK 64-Bit server VM:17.0.7.0:Eclipse Adoptium
                kernel.appcore.dll:AppModel API Host:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                lwjgl.dll
                management.dll:OpenJDK Platform binary:17.0.7.0:Eclipse Adoptium
                management_ext.dll:OpenJDK Platform binary:17.0.7.0:Eclipse Adoptium
                msvcp140.dll:Microsoft? C Runtime Library:14.27.29112.0 built by: vcwrkspc:Microsoft Corporation
                msvcp_win.dll:Microsoft? C Runtime Library:10.0.22621.608 (WinBuild.160101.0800):Microsoft Corporation
                msvcrt.dll:Windows NT CRT DLL:7.0.22621.608 (WinBuild.160101.0800):Microsoft Corporation
                mswsock.dll:Microsoft Windows Sockets 2.0 Service Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                napinsp.dll:E-mail Naming Shim Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                ncrypt.dll:Windows NCrypt Router:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                net.dll:OpenJDK Platform binary:17.0.7.0:Eclipse Adoptium
                netutils.dll:Net Win32 API Helpers DLL:10.0.22621.674 (WinBuild.160101.0800):Microsoft Corporation
                nio.dll:OpenJDK Platform binary:17.0.7.0:Eclipse Adoptium
                nlansp_c.dll:NLA Namespace Service Provider DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                ntdll.dll:NT Layer DLL:10.0.22621.1485 (WinBuild.160101.0800):Microsoft Corporation
                perfos.dll:Windows System Performance Objects DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                pfclient.dll:SysMain Client:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                pnrpnsp.dll:PNRP Name Space Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                profapi.dll:User Profile Basic API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                rasadhlp.dll:Remote Access AutoDial Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                shlwapi.dll:Shell Light-weight Utility Library:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                srvcli.dll:Server Service Client DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                sunmscapi.dll:OpenJDK Platform binary:17.0.7.0:Eclipse Adoptium
                ucrtbase.dll:Microsoft? C Runtime Library:10.0.22621.608 (WinBuild.160101.0800):Microsoft Corporation
                urlmon.dll:OLE32 Extensions for Win32:11.00.22621.1344 (WinBuild.160101.0800):Microsoft Corporation
                vcruntime140_1.dll:Microsoft? C Runtime Library:14.27.29112.0 built by: vcwrkspc:Microsoft Corporation
                verify.dll:OpenJDK Platform binary:17.0.7.0:Eclipse Adoptium
                win32u.dll:Win32u:10.0.22621.1555 (WinBuild.160101.0800):Microsoft Corporation
                windows.storage.dll:Microsoft WinRT Storage API:10.0.22621.608 (WinBuild.160101.0800):Microsoft Corporation
                winrnr.dll:LDAP RnR Provider DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                wintypes.dll:Windows Base Types DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                wshbth.dll:Windows Sockets Helper DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
                zip.dll:OpenJDK Platform binary:17.0.7.0:Eclipse Adoptium
Stacktrace:
        at net.minecraft.client.main.Main.main(Main.java:178)
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
        at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
        at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

-- System Details --
Details:
        Minecraft Version: 1.19.4
        Minecraft Version ID: 1.19.4
        Operating System: Windows 11 (amd64) version 10.0
        Java Version: 17.0.7, Eclipse Adoptium
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Eclipse Adoptium
        Memory: 184459696 bytes (175 MiB) / 480247808 bytes (458 MiB) up to 4271898624 bytes (4074 MiB)
        CPUs: 12
        Processor Vendor: AuthenticAMD
        Processor Name: AMD Ryzen 5 5600X 6-Core Processor
        Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
        Microarchitecture: Zen 3
        Frequency (GHz): 3.70
        Number of physical packages: 1
        Number of physical CPUs: 6
        Number of logical CPUs: 12
        Graphics card #0 name: NVIDIA GeForce GTX 950
        Graphics card #0 vendor: NVIDIA (0x10de)
        Graphics card #0 VRAM (MB): 2048.00
        Graphics card #0 deviceId: 0x1402
        Graphics card #0 versionInfo: DriverVersion=31.0.15.3161
        Memory slot #0 capacity (MB): 8192.00
        Memory slot #0 clockSpeed (GHz): 3.20
        Memory slot #0 type: DDR4
        Memory slot #1 capacity (MB): 8192.00
        Memory slot #1 clockSpeed (GHz): 3.20
        Memory slot #1 type: DDR4
        Virtual memory max (MB): 32104.77
        Virtual memory used (MB): 27317.51
        Swap memory total (MB): 15811.17
        Swap memory used (MB): 1821.79
        JVM Flags: 1 total; -XX:+ShowCodeDetailsInExceptionMessages
        Fabric Mods:
                fabric-api: Fabric API 0.79.0+1.19.4
                fabric-api-base: Fabric API Base 0.4.24+9ff28bcef4
                fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.25+49abcf7ef4
                fabric-biome-api-v1: Fabric Biome API (v1) 13.0.7+348a9c64f4
                fabric-block-api-v1: Fabric Block API (v1) 1.0.6+e022e5d1f4
                fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.34+c2e6f674f4
                fabric-client-tags-api-v1: Fabric Client Tags 1.0.15+1134c5b8f4
                fabric-command-api-v2: Fabric Command API (v2) 2.2.6+e719b857f4
                fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.9+ae0966baf4
                fabric-convention-tags-v1: Fabric Convention Tags 1.4.1+9a7c5daaf4
                fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.15+aeb40ebef4
                fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.4.0+6cebf059f4
                fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.45+7f87f8faf4
                fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.13+e45f7c65f4
                fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.43+a1ccd7bff4
                fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.33+a1ccd7bff4
                fabric-gametest-api-v1: Fabric Game Test API (v1) 1.2.4+ae0966baf4
                fabric-item-api-v1: Fabric Item API (v1) 2.1.17+09a3510cf4
                fabric-item-group-api-v1: Fabric Item Group API (v1) 3.0.5+043f9acff4
                fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.33+c477957ef4
                fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.15+5da15ca1f4
                fabric-loot-api-v2: Fabric Loot API (v2) 1.1.27+75e98211f4
                fabric-message-api-v1: Fabric Message API (v1) 5.1.1+1ee8be40f4
                fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.39+49abcf7ef4
                fabric-models-v0: Fabric Models (v0) 0.3.30+11ba9c3bf4
                fabric-networking-api-v1: Fabric Networking API (v1) 1.3.1+a6f3ccfaf4
                fabric-object-builder-api-v1: Fabric Object Builder API (v1) 7.0.3+63b515f4f4
                fabric-particles-v1: Fabric Particles (v1) 1.0.23+f1e4495bf4
                fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.8+a1ccd7bff4
                fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.0+670e8ac6f4
                fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.5+81e8c576f4
                fabric-renderer-indigo: Fabric Renderer - Indigo 1.1.1+81e8c576f4
                fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.28+afca2f3ef4
                fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.21+f1e4495bf4
                fabric-rendering-v1: Fabric Rendering (v1) 2.1.1+8f878217f4
                fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.1+e6c7d4eef4
                fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.2+1e1fb126f4
                fabric-screen-api-v1: Fabric Screen API (v1) 1.0.45+8c25edb4f4
                fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.20+5da15ca1f4
                fabric-sound-api-v1: Fabric Sound API (v1) 1.0.9+75e98211f4
                fabric-transfer-api-v1: Fabric Transfer API (v1) 3.1.1+da9bb835f4
                fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 3.0.3+63b515f4f4
                fabricloader: Fabric Loader 0.14.19
                firstmod: vtf6259's first mod ${version}
                java: OpenJDK 64-Bit Server VM 17
                minecraft: Minecraft 1.19.4
        Launched Version: Fabric
        Backend library: LWJGL version 3.3.1 SNAPSHOT
        Backend API: Unknown
        Window size: <not initialized>
        GL Caps: Using framebuffer using OpenGL 3.2
        GL debug messages: <disabled>
        Using VBOs: Yes
        Is Modded: Definitely; Client brand changed to 'fabric'
        Type: Client (map_client.txt)
        CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\vtf62\code\java\fabric\first mod\run\crash-reports\crash-2023-04-27_16.35.51-client.txt

**Comment by haykam821** [comment]
The class defined in your `main` entrypoint, `net.virgilsfirstmod.mod.firstmod`, does not seem to exist.

**Comment by vtf6259** [comment]
> 

Ty it was a naming error on my end it works now ty
