### ISSUE TITLE
help me 

### ISSUE THREAD

**Issue by jaguar4140** [FabricMC/fabric-example-mod#252]
Uncaught exception in thread "main"
java.lang.RuntimeException: Non-unique Mixin config name mixins.reach-entity-attributes.json used by the mods feudalw and reach-entity-attributes
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:90)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:153)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
