### ISSUE TITLE
crash report from my offline all alone world

### ISSUE THREAD

**Issue by balaachada** [FabricMC/fabric-example-mod#277]
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2024-03-24 13:40:33
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1282.method_48789(net.minecraft.class_6862)" because "$$0" is null
	at net.minecraft.class_1297.method_5679(class_1297.java:2702)
	at net.minecraft.class_1309.method_5643(class_1309.java:1132)
	at net.minecraft.class_1642.method_5643(class_1642.java:293)
	at com.alessandrv.alessandrvenchantments.util.CustomExplosion.DamageEntities(CustomExplosion.java:82)
	at com.alessandrv.alessandrvenchantments.enchantments.ExplosiveEnchantment.method_8178(ExplosiveEnchantment.java:82)
	at net.minecraft.class_1890.method_8198(class_1890.java:169)
	at net.minecraft.class_1890.method_17883(class_1890.java:138)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at net.minecraft.class_1890.method_8220(class_1890.java:138)
	at net.minecraft.class_1890.method_8209(class_1890.java:144)
	at net.minecraft.class_1890.method_8210(class_1890.java:171)
	at net.minecraft.class_1297.method_5723(class_1297.java:3119)
	at net.minecraft.class_1308.method_6121(class_1308.java:1480)
	at net.minecraft.class_1642.method_6121(class_1642.java:348)
	at net.minecraft.class_1366.method_6288(class_1366.java:151)
	at net.minecraft.class_1366.method_6268(class_1366.java:144)
	at net.minecraft.class_1396.method_6268(class_1396.java:28)
	at net.minecraft.class_4135.method_6268(class_4135.java:65)
	at net.minecraft.class_1355.method_38849(class_1355.java:120)
	at net.minecraft.class_1355.method_6275(class_1355.java:111)
	at net.minecraft.class_1308.method_6023(class_1308.java:775)
	at net.minecraft.class_1309.method_6007(class_1309.java:2697)
	at net.minecraft.class_1308.method_6007(class_1308.java:556)
	at net.minecraft.class_1588.method_6007(class_1588.java:44)
	at net.minecraft.class_1642.method_6007(class_1642.java:263)
	at net.minecraft.class_1309.method_5773(class_1309.java:2446)
	at net.minecraft.class_1308.method_5773(class_1308.java:357)
	at net.minecraft.class_1642.method_5773(class_1642.java:236)
	at net.minecraft.class_3218.method_18762(class_3218.java:761)
	at net.minecraft.class_1937.method_18472(class_1937.java:492)
	at net.minecraft.class_3218.method_31420(class_3218.java:399)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:363)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:948)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:845)
	at net.minecraft.class_1132.method_3748(class_1132.java:110)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:683)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_1297.method_5679(class_1297.java:2702)
	at net.minecraft.class_1309.method_5643(class_1309.java:1132)
	at net.minecraft.class_1642.method_5643(class_1642.java:293)
	at com.alessandrv.alessandrvenchantments.util.CustomExplosion.DamageEntities(CustomExplosion.java:82)
	at com.alessandrv.alessandrvenchantments.enchantments.ExplosiveEnchantment.method_8178(ExplosiveEnchantment.java:82)
	at net.minecraft.class_1890.method_8198(class_1890.java:169)
	at net.minecraft.class_1890.method_17883(class_1890.java:138)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at net.minecraft.class_1890.method_8220(class_1890.java:138)
	at net.minecraft.class_1890.method_8209(class_1890.java:144)
	at net.minecraft.class_1890.method_8210(class_1890.java:171)
	at net.minecraft.class_1297.method_5723(class_1297.java:3119)
	at net.minecraft.class_1308.method_6121(class_1308.java:1480)
	at net.minecraft.class_1642.method_6121(class_1642.java:348)
	at net.minecraft.class_1366.method_6288(class_1366.java:151)
	at net.minecraft.class_1366.method_6268(class_1366.java:144)
	at net.minecraft.class_1396.method_6268(class_1396.java:28)
	at net.minecraft.class_4135.method_6268(class_4135.java:65)
	at net.minecraft.class_1355.method_38849(class_1355.java:120)
	at net.minecraft.class_1355.method_6275(class_1355.java:111)
	at net.minecraft.class_1308.method_6023(class_1308.java:775)
	at net.minecraft.class_1309.method_6007(class_1309.java:2697)
	at net.minecraft.class_1308.method_6007(class_1308.java:556)
	at net.minecraft.class_1588.method_6007(class_1588.java:44)
	at net.minecraft.class_1642.method_6007(class_1642.java:263)
	at net.minecraft.class_1309.method_5773(class_1309.java:2446)
	at net.minecraft.class_1308.method_5773(class_1308.java:357)
	at net.minecraft.class_1642.method_5773(class_1642.java:236)
	at net.minecraft.class_3218.method_18762(class_3218.java:761)
	at net.minecraft.class_1937.method_18472(class_1937.java:492)
	at net.minecraft.class_3218.method_31420(class_3218.java:399)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)

-- Entity being ticked --
Details:
	Entity Type: minecraft:zombified_piglin (net.minecraft.class_1590)
	Entity ID: 1967
	Entity Name: Piglin-zumbi
	Entity's Exact location: -0.48, 109.00, 91.54
	Entity's Block location: World: (-1,109,91), Section: (at 15,13,11 in -1,6,5; chunk contains blocks -16,0,80 to -1,255,95), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.09
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:492)
	at net.minecraft.class_3218.method_31420(class_3218.java:399)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:363)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:948)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:845)
	at net.minecraft.class_1132.method_3748(class_1132.java:110)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:683)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Bala_Achada'/122, l='ServerLevel[New World]', x=-0.43, y=110.00, z=92.82]]
	Chunk stats: 6241
	Level dimension: minecraft:the_nether
	Derived: true
	Level spawn location: World: (0,168,0), Section: (at 0,8,0 in 0,10,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2886222 game time, 4183468 day time
	Level name: New World
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 53809 (now: false), thunder time: 91282 (now: false)
	Known server brands: fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
	Loaded entity count: 250
Stacktrace:
	at net.minecraft.class_3218.method_8538(class_3218.java:1681)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:951)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:845)
	at net.minecraft.class_1132.method_3748(class_1132.java:110)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:683)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 3020038112 bytes (2880 MiB) / 4999610368 bytes (4768 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce RTX 2060 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f06
	Graphics card #0 versionInfo: DriverVersion=31.0.15.5186
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 25529.06
	Virtual memory used (MB): 14860.34
	Swap memory total (MB): 9216.00
	Swap memory used (MB): 108.96
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		alessandrvenchantments: Alessandrv's Enchantments 1.5.2
		bobby: Bobby 5.1.0+mc1.20.4
			com_typesafe_config: config 1.4.2
			fabric-api-base: Fabric API Base 0.4.36+78d798af4f
			fabric-command-api-v2: Fabric Command API (v2) 2.2.20+78d798af4f
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		cloth-config: Cloth Config v13 13.0.121
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 15.0.0.2
		enchanted-vertical-slabs: Enchanted Vertical Slabs 1.9.2
		enchantinginfuser: Enchanting Infuser 20.4.0
		fabric-api: Fabric API 0.96.3+1.20.4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.49+82b1bb3e4f
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.16+78d798af4f
			fabric-block-api-v1: Fabric Block API (v1) 1.0.16+3e2216cb4f
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.4+78d798af4f
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.46+78d798af4f
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.7+78d798af4f
			fabric-command-api-v1: Fabric Command API (v1) 1.2.41+f71b366f4f
			fabric-commands-v0: Fabric Commands (v0) 0.2.58+df3654b34f
			fabric-containers-v0: Fabric Containers (v0) 0.1.86+df3654b34f
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.13+78d798af4f
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.10+78d798af4f
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.23+78d798af4f
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.2+b90db5744f
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.2.2+5c0133444f
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.61+78d798af4f
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+44c0f8c64f
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.1+389931eb4f
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.74+df3654b34f
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.46+78d798af4f
			fabric-item-api-v1: Fabric Item API (v1) 2.2.0+d6f2b0844f
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.24+f9b333cc4f
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.41+78d798af4f
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.39+df3654b34f
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.0+a67ffb5d4f
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.7+78d798af4f
			fabric-message-api-v1: Fabric Message API (v1) 6.0.5+78d798af4f
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.63+78d798af4f
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.8+78d798af4f
			fabric-models-v0: Fabric Models (v0) 0.4.7+9386d8a74f
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.7+2e5ac5484f
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.0.12+080016e44f
			fabric-particles-v1: Fabric Particles (v1) 1.1.7+78d798af4f
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.20+78d798af4f
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.18+78d798af4f
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.4+78d798af4f
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.4+78d798af4f
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.53+df3654b34f
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.42+73761d2e4f
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.1+e761c6694f
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.56+df3654b34f
			fabric-rendering-v1: Fabric Rendering (v1) 3.2.0+6fd945a04f
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.14+78d798af4f
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.18+b66dcf784f
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.17+78d798af4f
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.55+78d798af4f
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.17+78d798af4f
			fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.11+e84342304f
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.14+78d798af4f
		fabric-language-kotlin: Fabric Language Kotlin 1.10.18+kotlin.1.9.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.2
		fabricloader: Fabric Loader 0.15.7
			mixinextras: MixinExtras 0.3.5
		fallingtree: FallingTree 1.20.4.3
		forgeconfigapiport: Forge Config API Port 20.4.3
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		incendium: Incendium 5.3.4
		iris: Iris 1.6.17
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 17.3.0.49
		journeymap: Journeymap 5.9.20
			journeymap-api-fabric: JourneyMap API 1.20.2-1.9-fabric-SNAPSHOT
		lithium: Lithium 0.12.1
		merenc: Merge Enchantments 3.2
		minecraft: Minecraft 1.20.4
		modmenu: Mod Menu 9.0.0
		nullscape: Nullscape 1.2.4
		nvidium: Nvidium 0.2.6-beta
		puzzleslib: Puzzles Lib 20.4.41
		sodium: Sodium 0.5.8+mc1.20.4
		tectonic: Tectonic 2.1.2a
		terralith: Terralith 2.4.11
		yet_another_config_lib_v3: YetAnotherConfigLib 3.3.2+1.20.4
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		zoomify: Zoomify 2.13.0
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.5.1
			dev_isxander_settxi_settxi-core: settxi-core 2.10.6
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.6
	Loaded Shaderpack: ComplementaryReimagined_r5.1.1.zip
		Profile: Custom (+12 options changed by user)
	Server Running: true
	Player Count: 1 / 8; [class_3222['Bala_Achada'/122, l='ServerLevel[New World]', x=-0.43, y=110.00, z=92.82]]
	Data Packs: vanilla, fabric, enchanted-vertical-slabs, enchantinginfuser (incompatible), fabric-convention-tags-v1, incendium, nullscape, terralith, tectonic:terratonic_resourcepacks/terratonic (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.15.7-1.20.4

**Comment by balaachada** [comment]
i dont know how can i help, and even dont know if was your mods fault, but im trying to help the mod because i really liked

**Comment by Juuxel** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
