### ISSUE TITLE
Failing to run mod on local server

### ISSUE THREAD

**Issue by yentheo** [FabricMC/fabric-example-mod#42]
First off I would like to compliment the fabric initiative. But I'm having some trouble with running my mod on a server. I'm not sure if this is the right place for this but if it's not, please point me in the right direction.

I'm building a mod and I started by cloning the fabric-example-mod and I started in VS Code, as a side note, pretty cool how easy it was to get it up on running on VS Code, kudos to the fabric team. When I just start the debug task, the fabric launcher (if I'm not mistaken the fabric launcher is de program that runs the MC server?) pops up and the server is started and the mod is loaded.

You can find my fork of the example mod here btw https://github.com/yentheo/fabric-example-mod

Now I changed up the mod a little bit and added some dependencies like jackson-databind.
When I run the debug task, my server starts up fine and the mod runs fine too.

Now I wanted to try and setup a server from scratch without the debug task. So I downloaded the server installer from here https://fabricmc.net/use/ and did the installation. Now when I run `java -jar fabric-server-launch.jar` I get a running server. All is well. 

Now I want to publish my mod to run it in that server. But at this time I don't want to really publish it to any public repository. I just want to create a jar and put it inside the mods folder. So I run the `./gradlew build` task and I get my jar. I also download the fabric-api jar and put it inside the mods folder.

When starting the server at this point I get:
```
02:54:29] [main/INFO]: Loading for game Minecraft 20w08a
[02:54:30] [main/INFO]: [FabricLoader] Loading 4 mods: minecraft@1.16-alpha.20.8.a, fabric@0.4.33+build.299-1.16, fabricloader@0.7.8+build.184, modid@1.0.0
[02:54:30] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/Users/yentheoerlemans/fabric-server/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[02:54:36] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[02:54:36] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[02:54:36] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[02:54:36] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[02:54:36] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[02:54:36] [main/FATAL]: Failed to start the minecraft server
net.fabricmc.loader.api.EntrypointException: Could not look up entries for entrypoint main!
	at net.fabricmc.loader.EntrypointStorage.getEntrypoints(EntrypointStorage.java:153) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.FabricLoader.getEntrypoints(FabricLoader.java:220) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:41) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:34) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:32) ~[fabric-server-launch.jar:?]
	at net.minecraft.class_3176.<init>(class_3176.java:100) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:948) [intermediary-server.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26) [fabric-server-launch.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49) [fabric-server-launch.jar:?]
	Suppressed: java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/type/TypeReference
		at java.lang.Class.forName0(Native Method) ~[?:?]
		at java.lang.Class.forName(Class.java:398) ~[?:?]
		at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45) ~[fabric-server-launch.jar:?]
		at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:100) ~[fabric-server-launch.jar:?]
		at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:92) ~[fabric-server-launch.jar:?]
		at net.fabricmc.loader.EntrypointStorage.getEntrypoints(EntrypointStorage.java:143) ~[fabric-server-launch.jar:?]
		at net.fabricmc.loader.FabricLoader.getEntrypoints(FabricLoader.java:220) ~[fabric-server-launch.jar:?]
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:41) ~[fabric-server-launch.jar:?]
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:34) ~[fabric-server-launch.jar:?]
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:32) ~[fabric-server-launch.jar:?]
		at net.minecraft.class_3176.<init>(class_3176.java:100) ~[intermediary-server.jar:?]
		at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:948) [intermediary-server.jar:?]
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
		at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
		at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
		at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193) [fabric-server-launch.jar:?]
		at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138) [fabric-server-launch.jar:?]
		at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26) [fabric-server-launch.jar:?]
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
		at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
		at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
		at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61) [fabric-server-launch.jar:?]
		at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105) [fabric-server-launch.jar:?]
		at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49) [fabric-server-launch.jar:?]
	Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.type.TypeReference
		at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583) ~[?:?]
		at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
		at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:56) ~[fabric-server-launch.jar:?]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
		at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161) ~[fabric-server-launch.jar:?]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
		... 26 more
```

I don't think publishing works like I think it works but I could not find a comprehensive guide in the docs and I'm a bit of a noob in the java world.

What I can make of it is that it can't find the extra dependencies I added to the build.gradle file like the jackson-databind stuff.

What am I doing wrong? Thanks in advance!

**Comment by liach** [comment]
Well, when the mod is packaged, dependencies are not included by default. Use `include` configuration in addition to compile classpath configurations for the libraries you need to ship at runtime.

**Comment by yentheo** [comment]
Thanks for you answer but as I said, I'm a bit of a Java noob.
How would I go about that. I found something about include here:
https://fabricmc.net/wiki/documentation:fabric_loom?s[]=include
But do I need to put an include under my dependencies section like this:
```
dependencies {
	//to change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modCompile "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API. This is technically optional, but you probably want it anyway.
	modCompile "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
	compile "org.java-websocket:Java-WebSocket:1.4.0"

	implementation "com.squareup.okhttp3:okhttp:4.4.0"
  	implementation 'com.google.code.gson:gson:2.8.6'
	implementation 'com.fasterxml.jackson.core:jackson-databind:2.9.9'
	implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.9.9'

	include "com.squareup.okhttp3:okhttp:4.4.0"
  	include 'com.google.code.gson:gson:2.8.6'
	include 'com.fasterxml.jackson.core:jackson-databind:2.9.9'
	include 'com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.9.9'
}
```
When I build with this configuration, my jar suddenly goes from 16KB tot 2.2MB, so I guess the jars are included now.

On startup of the server it says: 
```
[13:44:52] [main/INFO]: [FabricLoader] Loading 8 mods: minecraft@1.16-alpha.20.8.a, com_squareup_okhttp3_okhttp@4.4.0, com_fasterxml_jackson_dataformat_jackson-dataformat-yaml@2.9.9, fabric@0.4.33+build.299-1.16, fabricloader@0.7.8+build.184, com_google_code_gson_gson@2.8.6, com_fasterxml_jackson_core_jackson-databind@2.9.9, modid@1.0.0
```
I'm not sure it should but that's a difference from before. But then it still crashes with the same error as before.

**Comment by modmuss50** [comment]
Note include is none trasitive, so it wont pull in deps of the specified deps.

Looking here [https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind/2.10.2](https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind/2.10.2) you can see that jackson-databind also depends on `jackson-core`.

With implementation it will pull this in without knowing it, with include you need to specify every single dep to be included. This is done to prevent you accidentially pulling in stuff you dont want.

**Comment by yentheo** [comment]
Well thanks for the speedy response. I added the core as include like so:
```
dependencies {
	//to change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modCompile "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API. This is technically optional, but you probably want it anyway.
	modCompile "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
	compile "org.java-websocket:Java-WebSocket:1.4.0"

	compile "com.squareup.okhttp3:okhttp:4.4.0"
  	compile 'com.google.code.gson:gson:2.8.6'
	compile 'com.fasterxml.jackson.core:jackson-databind:2.9.9'
	compile 'com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.9.9'
	
	include 'com.fasterxml.jackson.core:jackson-core:2.9.9'
}
```
Now it does not fail on the same error as above but now it can't find something from fabric api

```
Suppressed: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/registry/CommandRegistry
```

But I would assume placing the fabric api jar inside of the mods folder should've fixed this.
![image](https://user-images.githubusercontent.com/3296535/75550982-64d90e80-5a33-11ea-9a05-f5fb5189c786.png)

**Comment by modmuss50** [comment]
Yes, you will also need to have fabric api in the mods folder.

**Comment by yentheo** [comment]
But I have the fabric api jar in my foldder, but I still get the error 
```
Suppressed: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/registry/CommandRegistry
```

**Comment by liach** [comment]
The api jar should be downloaded from curseforge (a fat jar)

**Comment by yentheo** [comment]
That was it, I had my fabric api jar from 
`https://maven.fabricmc.net/net/fabricmc/fabric-api/fabric-api/`
Getting it from curseforge fixed it, Thanks!
