### ISSUE TITLE
Cannot run from IDE

### ISSUE THREAD

**Issue by beyonik** [FabricMC/fabric-example-mod#44]
Mod itself builds just fine, but the game won't launch because it can't find LWJGL / GLFW.
I've tried both the auto generator, the MinecraftDev plugin, and manually setting this repo up, all to no avail.

```
warning: dev-launch-injector in pass-through mode, missing or unreadable config file (E:\ModȌreating\.gradle\loom-cache\launch.cfg)
[15:20:33] [main/INFO]: Loading for game Minecraft 1.15.2
[15:20:33] [main/INFO]: [FabricLoader] Loading 2 mods: minecraft@1.15.2, fabricloader@0.7.8+build.187
[15:20:33] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/David/.gradle/caches/modules-2/files-2.1/net.fabricmc/sponge-mixin/0.8+build.18/af077ad2845a00cde186fa2c99c4dd32bd2a2766/sponge-mixin-0.8+build.18.jar Service=Knot/Fabric Env=CLIENT
[15:20:34] [main/INFO]: Setting user: Player458
[15:20:37] [main/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[15:20:37] [main/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[15:20:37] [main/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 3/16/20 3:20 PM
Description: Initializing game

java.lang.ExceptionInInitializerError
	at net.minecraft.client.options.GameOptions.<init>(GameOptions.java:221)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:363)
	at net.minecraft.client.main.Main.main(Main.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Caused by: java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: Failed to locate library: lwjgl.dll
	at net.minecraft.client.util.InputUtil.<clinit>(InputUtil.java:109)
	... 11 more
Caused by: java.lang.UnsatisfiedLinkError: Failed to locate library: lwjgl.dll
	at org.lwjgl.system.Library.loadSystem(Library.java:147)
	at org.lwjgl.system.Library.loadSystem(Library.java:67)
	at org.lwjgl.system.Library.<clinit>(Library.java:50)
	at org.lwjgl.system.MemoryAccessJNI.<clinit>(MemoryAccessJNI.java:13)
	at org.lwjgl.system.Pointer.<clinit>(Pointer.java:28)
	at org.lwjgl.system.Platform.mapLibraryNameBundled(Platform.java:80)
	at org.lwjgl.glfw.GLFW.<clinit>(GLFW.java:674)
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue(DirectMethodHandle.java:330)
	at java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue(DirectMethodHandle.java:327)
	at java.lang.ClassValue.getFromHashMap(ClassValue.java:227)
	at java.lang.ClassValue.getFromBackup(ClassValue.java:209)
	at java.lang.ClassValue.get(ClassValue.java:115)
	at java.lang.invoke.DirectMethodHandle.checkInitialized(DirectMethodHandle.java:351)
	at java.lang.invoke.DirectMethodHandle.ensureInitialized(DirectMethodHandle.java:341)
	at java.lang.invoke.DirectMethodHandle.ensureInitialized(DirectMethodHandle.java:373)
	at net.minecraft.client.util.InputUtil.<clinit>(InputUtil.java:106)
	... 11 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.options.GameOptions.<init>(GameOptions.java:221)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:363)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 555676384 bytes (529 MB) / 731381760 bytes (697 MB) up to 1897922560 bytes (1810 MB)
	CPUs: 12
	JVM Flags: 0 total; 
	Launched Version: Fabric
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: ~~ERROR~~ NoClassDefFoundError: Could not initialize class org.lwjgl.glfw.GLFW
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# E:\Mod creating\Item Previews\run\.\crash-reports\crash-2020-03-16_15.20.37-client.txt

Process finished with exit code -1

```

**Comment by JamiesWhiteShirt** [comment]
> warning: dev-launch-injector in pass-through mode, missing or unreadable config file (E:\ModȌreating\.gradle\loom-cache\launch.cfg)

Loom should have generated this file at some point, but it's missing. Did you run any Gradle tasks when setting up?

**Comment by modmuss50** [comment]
My guess is the `Ȍ` is causing issues, is that the folder name? or is it an issue with DLI encoding/decoding?

**Comment by modmuss50** [comment]
Edit: looking further down the stacktrace the dir name is `Mod creating` so not sure where the `Ȍ` is coming from.

**Comment by beyonik** [comment]
I ran gradlew idea and then gradlew genSources while setting up @JamiesWhiteShirt

**Comment by JamiesWhiteShirt** [comment]
We have determined this is an issue with Fabric Loom. For now, you should be able to work around it by tweaking your run configurations. Look for an option named `-Dfabric.dli.config=E:\ModȌreating\.gradle\loom-cache\launch.cfg` and replace the "Ȍ" with " c" (`-Dfabric.dli.config=E:\Mod creating\.gradle\loom-cache\launch.cfg`)

**Comment by beyonik** [comment]
Thank you so much for the swift response! That works wonderfully.

**Comment by modmuss50** [comment]
A real fix should now be out.
