### ISSUE TITLE
java.lang.NoSuchMethodError (CrashReportSection method_577) on IntelliJ

### ISSUE THREAD

**Issue by SomeoneInParticular** [FabricMC/fabric-example-mod#58]
Seems a mixin somewhere is awry at the moment, as the repo (direct ZIP download and open, at time of writing) throws a "NoSuchMethod" exception. The mod compiles just fine, however, with no errors, with both IntelliJ and Gradle mediated "Build and Run" settings (I tried both, just to be safe). The full log of up to the error can be seen [here](https://github.com/FabricMC/fabric-example-mod/files/4855237/latest.log), with the debug log [here](https://github.com/FabricMC/fabric-example-mod/files/4855247/debug.log). The error message is as follows:

```java
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:194)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	... 3 more
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.util.crash.CrashReportSection net.minecraft.util.crash.CrashReportSection.method_577(java.lang.String, net.minecraft.util.crash.CrashCallable)'
	at net.minecraft.util.crash.CrashReport.handler$zej000$fillSystemDetails(CrashReport.java:541)
	at net.minecraft.util.crash.CrashReport.fillSystemDetails(CrashReport.java:72)
	at net.minecraft.util.crash.CrashReport.<init>(CrashReport.java:38)
	at net.minecraft.util.crash.CrashReport.initCrashReport(CrashReport.java:270)
	at net.minecraft.client.main.Main.main(Main.java:122)
	... 8 more

Process finished with exit code 1
```

Best Regards

**Comment by i509VCB** [comment]
What seems odd is that nothing installed should be breaking crash logs. Even more weird is how the crash report method does not exist.

**Comment by Kruemmelspalter** [comment]
I also have this issue

**Comment by NotRennaru** [comment]
Same i got this error

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
