### ISSUE TITLE
got exceptions when I tried to build the project with the command "gradlew gensources"

### ISSUE THREAD

**Issue by Kcalb35** [FabricMC/fabric-example-mod#60]
Below are the reports , I guess it might be somthing wrong with the json, or the reason lies in my computer settings.

> Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 32300 path $.libraries[50].downloads.classifiers.nat
ives-windows.path
        at com.google.gson.Gson.fromJson(Gson.java:942)
        at com.google.gson.Gson.fromJson(Gson.java:865)
        at net.fabricmc.loom.providers.MinecraftProvider.provide(MinecraftProvider.java:78)
        at net.fabricmc.loom.util.LoomDependencyManager.lambda$handleDependencies$1(LoomDependencyManager.java:111)
        ... 138 more
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 32300 path $.libraries[50].downloads.classifiers.natives-windows.path
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
        at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1031)
        at com.google.gson.stream.JsonReader.nextString(JsonReader.java:815)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:702)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:723)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:723)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:723)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:698)
        at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:894)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.Gson.fromJson(Gson.java:927)

**Comment by Kcalb35** [comment]
Here is a short version of the report

> What went wrong:
A problem occurred configuring root project 'fabric-example-mod'.
> Failed to provide com.mojang:minecraft:1.16.1 : com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 32300 path $.libraries[50].downloads.classifiers.n
atives-windows.path
