### ISSUE TITLE
opengl error: net.minecraft.client.util.Window$GlErroredException: GLFW error 65542: WGL: The driver does not appear to support OpenGL

### ISSUE THREAD

**Issue by thegame4craft** [FabricMC/fabric-example-mod#96]
Hello, i tryed to setup a project in intelji and uses the https://fabricmc.net/wiki/tutorial:setup docs (and a youtube video.) but if i run i getting follow error: 

`Connected to the target VM, address: '127.0.0.1:54406', transport: 'socket'
Java HotSpot(TM) 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
[17:04:51] [main/INFO] (FabricLoader) Loading for game Minecraft 1.16.5
[17:04:53] [main/INFO] (Fabric|Loader) [FabricLoader] Loading 48 mods: minecraft@1.16.5, fabric-screen-handler-api-v1@1.1.5+9354966b7d, fabric-networking-blockentity-v0@0.2.8+ca58154a7d, fabric-renderer-api-v1@0.4.2+2868a2287d, fabric-keybindings-v0@0.2.1+ca58154a7d, fabric-command-api-v1@1.1.1+351679a77d, fabricloader@0.11.3, fabric-screen-api-v1@1.0.0+c045166c7d, fabric-tool-attribute-api-v1@1.2.6+ca58154a7d, fabric-renderer-indigo@0.4.4+ca58154a7d, fabric-structure-api-v1@1.1.4+ca58154a7d, fabric-containers-v0@0.1.11+9354966b7d, fabric-dimensions-v1@2.0.6+9354966b7d, fabric-object-builder-api-v1@1.9.4+9354966b7d, java@12, fabric-events-interaction-v0@0.4.2+ca58154a7d, fabric-crash-report-info-v1@0.1.3+ca58154a7d, fabric-item-api-v1@1.2.1+ca58154a7d, fabric-game-rule-api-v1@1.0.6+ca58154a7d, fabric-entity-events-v1@1.0.3+ca58154a7d, fabric-api-base@0.2.1+9354966b7d, fabric-rendering-v0@1.1.2+ca58154a7d, fabric-key-binding-api-v1@1.0.4+9354966b7d, fabric-rendering-v1@1.6.0+2868a2287d, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, fabric-resource-loader-v0@0.4.6+2868a2287d, fabric-textures-v0@1.0.6+ca58154a7d, fabric-content-registries-v0@0.2.1+ca58154a7d, fabric-tag-extensions-v0@1.1.1+ca58154a7d, fabric-biome-api-v1@3.1.1+ca58154a7d, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, fabric-commands-v0@0.2.2+ca58154a7d, fabric-registry-sync-v0@0.7.4+ca58154a7d, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, fabric-mining-levels-v0@0.1.3+ca58154a7d, fabric-renderer-registries-v1@2.2.1+ca58154a7d, fabric-networking-api-v1@1.0.1+ca58154a7d, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, fabric-loot-tables-v1@1.0.2+ca58154a7d, fabric@0.32.5+1.16, fabrictest@0.0.1, fabric-item-groups-v0@0.2.5+351679a77d, fabric-models-v0@0.2.1+ca58154a7d, fabric-particles-v1@0.2.4+ca58154a7d, fabric-object-builders-v0@0.7.2+ca58154a7d, fabric-networking-v0@0.3.2+ca58154a7d, fabric-api-lookup-api-v1@1.0.0+dc716ea17d
[17:04:54] [main/INFO] (mixin) SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/Robin/.gradle/caches/modules-2/files-2.1/net.fabricmc/sponge-mixin/0.9.2+mixin.0.8.2/12c437eebf031967eaa7daad861e115932772cc7/sponge-mixin-0.9.2+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[17:04:54] [main/INFO] (Fabric|MixinBootstrap) Loaded Fabric development mappings for mixin remapper!
[17:04:56] [main/INFO] (mixin) Remapping refMap fabric-networking-blockentity-v0-refmap.json using remapper chain
[17:04:56] [main/INFO] (mixin) Remapping refMap fabric-screen-handler-api-v1-refmap.json using remapper chain
[17:04:56] [main/INFO] (mixin) Remapping refMap fabric-lifecycle-events-v1-refmap.json using remapper chain
[17:04:56] [main/INFO] (mixin) Remapping refMap fabric-containers-v0-refmap.json using remapper chain
[17:04:56] [main/INFO] (mixin) Remapping refMap fabric-renderer-indigo-refmap.json using remapper chain
[17:04:56] [main/INFO] (mixin) Remapping refMap fabric-rendering-data-attachment-v1-refmap.json using remapper chain
[17:04:56] [main/INFO] (mixin) Remapping refMap fabric-structure-api-v1-refmap.json using remapper chain
[17:04:56] [main/INFO] (mixin) Remapping refMap fabric-events-interaction-v0-refmap.json using remapper chain
[17:04:56] [main/INFO] (mixin) Remapping refMap fabric-item-api-v1-refmap.json using remapper chain
[17:04:57] [main/INFO] (mixin) Remapping refMap fabric-loot-tables-v1-refmap.json using remapper chain
[17:04:57] [main/INFO] (mixin) Remapping refMap fabric-object-builder-api-v1-refmap.json using remapper chain
[17:04:57] [main/INFO] (mixin) Remapping refMap fabric-screen-api-v1-refmap.json using remapper chain
[17:04:57] [main/INFO] (mixin) Remapping refMap fabric-dimensions-v1-refmap.json using remapper chain
[17:04:57] [main/INFO] (mixin) Remapping refMap fabric-renderer-registries-v1-refmap.json using remapper chain
[17:04:57] [main/INFO] (mixin) Remapping refMap fabric-textures-v0-refmap.json using remapper chain
[17:04:57] [main/INFO] (mixin) Remapping refMap fabric-registry-sync-v0-refmap.json using remapper chain
[17:04:57] [main/INFO] (mixin) Remapping refMap fabric-models-v0-refmap.json using remapper chain
[17:04:57] [main/INFO] (mixin) Remapping refMap fabric-blockrenderlayer-v1-refmap.json using remapper chain
[17:04:57] [main/INFO] (mixin) Remapping refMap fabric-renderer-api-v1-refmap.json using remapper chain
[17:04:57] [main/INFO] (mixin) Remapping refMap fabric-containers-v0-refmap.json using remapper chain
[17:04:57] [main/INFO] (mixin) Remapping refMap fabric-rendering-fluids-v1-refmap.json using remapper chain
[17:04:57] [main/INFO] (mixin) Remapping refMap fabric-biome-api-v1-refmap.json using remapper chain
[17:04:57] [main/INFO] (mixin) Remapping refMap fabric-resource-loader-v0-refmap.json using remapper chain
[17:04:57] [main/INFO] (mixin) Remapping refMap fabric-game-rule-api-v1-refmap.json using remapper chain
[17:04:57] [main/INFO] (mixin) Remapping refMap fabric-networking-api-v1-refmap.json using remapper chain
[17:04:57] [main/INFO] (mixin) Remapping refMap fabric-particles-v1-refmap.json using remapper chain
[17:04:57] [main/INFO] (mixin) Remapping refMap fabric-object-builders-refmap.json using remapper chain
[17:04:57] [main/INFO] (mixin) Remapping refMap fabric-tag-extensions-v0-refmap.json using remapper chain
[17:04:57] [main/INFO] (mixin) Remapping refMap fabric-tool-attribute-api-v1-refmap.json using remapper chain
[17:04:57] [main/INFO] (mixin) Remapping refMap fabric-rendering-v1-refmap.json using remapper chain
[17:04:57] [main/INFO] (mixin) Remapping refMap fabric-item-groups-v0-refmap.json using remapper chain
[17:04:57] [main/INFO] (mixin) Remapping refMap fabric-content-registries-v0-refmap.json using remapper chain
[17:04:57] [main/INFO] (mixin) Remapping refMap fabric-command-api-v1-refmap.json using remapper chain
[17:04:57] [main/INFO] (mixin) Remapping refMap fabric-crash-report-info-v1-refmap.json using remapper chain
[17:04:57] [main/INFO] (mixin) Remapping refMap fabric-api-lookup-api-v1-refmap.json using remapper chain
[17:04:57] [main/INFO] (mixin) Remapping refMap fabric-entity-events-v1-refmap.json using remapper chain
[17:04:57] [main/INFO] (mixin) Remapping refMap fabric-key-binding-api-v1-refmap.json using remapper chain
[17:04:57] [main/INFO] (mixin) Remapping refMap fabric-renderer-api-v1-refmap.json using remapper chain
[17:04:57] [main/WARN] (mixin) @Mixin target net/minecraft/client/render/block/BlockModelRenderer$AmbientOcclusionCalculator is public in fabric-renderer-indigo.mixins.json:MixinAmbientOcclusionCalculator and should be specified in value
[17:04:57] [main/WARN] (mixin) @Mixin target net/minecraft/client/render/chunk/ChunkBuilder$BuiltChunk$RebuildTask is public in fabric-renderer-indigo.mixins.json:MixinChunkRebuildTask and should be specified in value
[17:04:58] [main/WARN] (mixin) @Mixin target net/minecraft/village/TradeOffers$TypeAwareBuyForOneEmeraldFactory is public in fabric-object-builder-v1.mixins.json:TypeAwareTradeMixin and should be specified in value
[17:04:59] [main/WARN] (mixin) @Mixin target net/minecraft/client/font/FontManager$1 is public in fabric-resource-loader-v0.mixins.json:client.FontManagerResourceReloadListenerMixin and should be specified in value
[17:04:59] [main/WARN] (mixin) @Mixin target net/minecraft/server/command/GameRuleCommand$1 is public in fabric-game-rule-api-v1.mixins.json:GameRuleCommandVisitorMixin and should be specified in value
[17:05:00] [main/WARN] (mixin) @Mixin target net/minecraft/client/gui/screen/world/EditGameRulesScreen$RuleListWidget$1 is public in fabric-game-rule-api-v1.mixins.json:client.RuleListWidgetVisitorMixin and should be specified in value
[17:05:00] [main/WARN] (mixin) @Mixin target net/minecraft/server/world/ThreadedAnvilChunkStorage$EntityTracker is public in fabric-networking-api-v1.mixins.json:accessor.EntityTrackerAccessor and should be specified in value
[17:05:00] [main/WARN] (mixin) @Mixin target net/minecraft/client/particle/ParticleManager$SimpleSpriteProvider is public in fabric-particles-v1.mixins.json:ParticleManagerAccessor$SimpleSpriteProviderAccessor and should be specified in value
[17:05:00] [main/WARN] (mixin) @Mixin target net/minecraft/tag/Tag$1 is public in fabric-tag-extensions-v0.mixins.json:MixinTagImpl and should be specified in value
[17:05:00] [main/WARN] (mixin) @Mixin target net/minecraft/tag/RequiredTagList$TagWrapper is public in fabric-tag-extensions-v0.mixins.json:MixinTagImpl and should be specified in value
[17:05:36] [main/INFO] (Minecraft) Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[17:05:41] [main/ERROR] (Minecraft) Failed to verify authentication
 com.mojang.authlib.exceptions.AuthenticationUnavailableException: null
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.checkPrivileges(YggdrasilSocialInteractionsService.java:97) ~[authlib-2.1.28.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.<init>(YggdrasilSocialInteractionsService.java:40) ~[authlib-2.1.28.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createSocialInteractionsService(YggdrasilAuthenticationService.java:152) ~[authlib-2.1.28.jar:?]
	at net.minecraft.client.MinecraftClient.method_31382(MinecraftClient.java:625) [minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.6-v2.jar:?]
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:409) [minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.6-v2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:177) [minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.6-v2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
[17:05:41] [main/INFO] (Minecraft) Setting user: Player144
[17:05:42] [main/INFO] (Minecraft) [STDOUT]: Hello Fabric world!
[17:05:43] [main/INFO] (Indigo) [Indigo] Registering Indigo renderer!
[17:05:47] [main/INFO] (Minecraft) Backend library: LWJGL version 3.2.2 build 10
[17:05:51] [main/WARN] (Minecraft) Failed to create window: 
 net.minecraft.client.util.Window$GlErroredException: GLFW error 65542: WGL: The driver does not appear to support OpenGL
	at net.minecraft.client.util.Window.throwGlError(Window.java:216) ~[minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.6-v2.jar:?]
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokePPPP(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1714) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1897) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at net.minecraft.client.util.Window.<init>(Window.java:90) ~[minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.6-v2.jar:?]
	at net.minecraft.client.util.WindowProvider.createWindow(WindowProvider.java:21) ~[minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.6-v2.jar:?]
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:461) ~[minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.6-v2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:177) [minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.6-v2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
Disconnected from the target VM, address: '127.0.0.1:54406', transport: 'socket'

Process finished with exit code 0
`

I have searched on the internet but i didn't found anything.

**Comment by thegame4craft** [comment]
i have the soulution: i need to run this with jdk 1.8u262

**Comment by actuallyasmartname** [comment]
The driver does not appear to support OpenGL

I've had this problem with my Radeon M570 on my laptop, the solution was to switch to my Intel HD 530 hehe

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
